---
title: "WordPress Agents Exploratory Analysis - Part II"
author: "Viviane Schneider"
date: "07/29/2019"
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---
**Type of Analysis:** Descriptive analysis - Bivariate description

**Source:** Data come from WordPress Report Trac System.
[URL Source](https://core.trac.wordpress.org/query?status=accepted&status=assigned&status=new&status=reopened&status=reviewing&col=id&col=summary&col=status&col=owner&col=type&col=priority&col=milestone&col=component&col=version&col=severity&col=resolution&col=time&col=changetime&col=focuses&col=reporter&col=keywords&order=priority)
**Dataframe:** [GitHub Repository](https://raw.githubusercontent.com/vivianesch/CoherenceAnalysisWordPress/master/TicketW.csv)

**Date collection:** 04/07/2019.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```


**1. EXPLORATORY ANALYSIS -BIVARIABLE ANALYSIS** 

```{r echo=FALSE}
#Load
library(readr)
library(dplyr)
library(plotly)
library(ggplot2)
library(tidyr)
library(knitr)
library(rmarkdown)
library(data.table)

```


```{r Read}

#READ DATA
TicketW <- read_csv('~/PhD Analysis/1. PhD escriptive exploratory analysis/TicketW.csv')
View(TicketW) # Read 
glimpse(TicketW)

```


```{r echo=FALSE}

#Bring old functions and variables

.Unianalysis = function (x) {
        
        y<-table(x)
        y<-as.data.frame(as.table(y))
        general_prop<-prop.table(y$Freq) #Proportion
        y<-data.frame(y, general_prop) 
        return(y)
}#1. Filter the most active group of reporters (Which reporter with more than 10 tickets) 
    .GroupActive = function(x) {
        y = filter(x, Freq>10)
        x <- y[order(y$Freq, decreasing = TRUE),]
        group_prop<-prop.table(x$Freq) #Proportion
        x<-data.frame(x,group_prop) 
        return(x)
    }
#2. Filter the median active group
    .GroupMedian = function(x) {
        y = filter(x, Freq<10 & Freq>4)
        x <- y[order(y$Freq, decreasing = TRUE),]
        group_prop<-prop.table(x$Freq) #Proportion
        x<-data.frame(x,group_prop)
        return(x)
    }  
#3. Filter the less active group 
     .GroupAlien = function(x) {
        y = filter(x, Freq<4)
        group_prop<-prop.table(x$Freq) #Proportion
        x<-data.frame(x,group_prop)
        x <- y[order(y$Freq, decreasing = TRUE),]
        return(x)
     }
     
#Bring the Reporter variables
     
Reporter<-.Unianalysis(TicketW$Reporter) 
totalReporter<-nrow(Reporter)

ActiveReporters<-.GroupActive(Reporter)
totalAR<-nrow(ActiveReporters)

MedianReporters<-.GroupMedian(Reporter)
totalMR<-nrow(MedianReporters)

LessReporters<-.GroupAlien(Reporter)
totalLR<-nrow(LessReporters)

#Bring the Owner variables

Owner<-.Unianalysis(TicketW$Owner) 
totalReporter<-nrow(Reporter)

ActiveOwners<-.GroupActive(Owner)
totalAR<-nrow(ActiveReporters)

MedianOwners<-.GroupMedian(Owner)
totalMR<-nrow(MedianReporters)

LessOwners<-.GroupAlien(Owner)
totalLR<-nrow(LessOwners)

```


**Functions** 

```{r Bi_analysis}
#Bivariable analysis

#Functions
    #Function .List.f.filter() make variable set that will be filtered
    .List.f.filter = function(x){
        nr<-nrow(x)#Quantity of members
          y<-x[1:nr,1:1] #Select array of members names to filter 
            z<-as.character(y) #Transform names into caracter array
    return(z)
    }
    
    # Function .List.w.Group() Select two key valiables for each group and return a list of inter-ralation of it
    # Where:  x is dataframe with 2 colunms of variables
    # y is a variable yo want to extract a list in order to filter a group
    # f is a list of the group achieve from Function .List.f.filter()
    .Top.15.Group = function(x,y,f){
        z = subset(x, y %in% f) 
        z<-table(z[ ,2],z[ ,1])
          d<-dim(z)
            w<-rowSums(z[1:d[1],1:d[2]])
            w<-as.data.frame(as.table(w)) # Transform to a data frame
            w<- w[order(w$Freq, decreasing = TRUE),] #Ranking
            w<-w[1:15,1:2] #Filter top 10
    return(w)
    }  

 
```


**1 REPORTERS AND KEYWORDS ANALYSIS:** 


```{r Bi_a_Reporters}

    #1.Analyse Keywords used for Active reporters
    Reporter_Keywords<- TicketW %>% select(Reporter,Keywords) #Table of Reporters and Keywords
    summary(Reporter_Keywords)
    dim(Reporter_Keywords)
    glimpse(Reporter_Keywords)
    
#1.1 Analyse Keywords used for Active reporters
 
     AR<-.List.f.filter(ActiveReporters)
    # 10 top Keywords used by Active Group
Most_Key_AR<-.Top.15.Group(Reporter_Keywords,Reporter_Keywords$Reporter,AR) 

   #1.2 Analyse Keywords used for Median reporters
    MR<-.List.f.filter(MedianReporters)
    # 10 top Keywords used by Median Group
Most_Key_MR<-.Top.15.Group(Reporter_Keywords,Reporter_Keywords$Reporter,MR) 
    
#1.3 Analyse Keywords used for Alien reporters
    LR<-.List.f.filter(LessReporters)
    # 10 top Keywords used by Alien Group 
Most_Key_LR<-.Top.15.Group(Reporter_Keywords,Reporter_Keywords$Reporter,LR) 


```

**2 OWNERS AND KEYWORDS ANALYSIS:** 

```{r Bi_a_Owners}

#2.Analyse Keywords used for Active owners

    Owner_Keywords<- TicketW %>% select(Owner,Keywords) #Table of Reporters and Keywords
    summary(Owner_Keywords)
    dim(Owner_Keywords)
    glimpse(Owner_Keywords)

#2.1 Analyse Keywords used for Active Owners
     AO<-.List.f.filter(ActiveOwners)
    # 10 top Keywords used by Active Group
Most_Key_AO<-.Top.15.Group(Owner_Keywords,Owner_Keywords$Owner,AO) 

#2.2 Analyse Keywords used for Median reporters
    MO<-.List.f.filter(MedianOwners)
    # 10 top Keywords used by Median Group
Most_Key_MO<-.Top.15.Group(Owner_Keywords,Owner_Keywords$Owner,MO) 
    
#2.3 Analyse Keywords used for Alien Owner
    LO<-.List.f.filter(LessOwners)
    # 10 top Keywords used by Alien Group 
Most_Key_LO<-.Top.15.Group(Owners_Keywords,Owner_Keywords$Owners,LO) 

```

**3 REPORTERS AND OWNERS KEYWORDS GRAPHICS:** 

```{r Graphics}

library(SnowballC)
library(wordcloud)
library(RColorBrewer)

    #Graphics of most frequent group words of Reporters 
    #Active Group
          barplot(Most_Key_AR$Freq, las = 2, names.arg = Most_Key_AR$Var1,
                  col ="lightblue", main ="Freq. words of Active Reporters",
                  ylab = "Word frequencies")
          set.seed(1)
          wordcloud(words = Most_Key_AR$Var1, freq = Most_Key_AR$Freq, min.freq = 1,
                    max.words=15, random.order=FALSE, rot.per=0.35, 
                    colors=brewer.pal(8, "Dark2"))
          
          #Median Group
          barplot(Most_Key_MR$Freq, las = 2, names.arg = Most_Key_MR$Var1,
                  col ="lightgreen", main ="Freq. words of Median Reporters",
                  ylab = "Word frequencies")
          
          set.seed(1)
          wordcloud(words = Most_Key_MR$Var1, freq = Most_Key_MR$Freq, min.freq = 1,
                    max.words=15, random.order=FALSE, rot.per=0.35, 
                    colors=brewer.pal(8, "Dark2"))
          
           #Alien Group
          barplot(Most_Key_LR$Freq, las = 2, names.arg = Most_Key_LR$Var1,
                  col ="deeppink1", main ="Freq. words of Median Reporters",
                  ylab = "Word frequencies")
          
          set.seed(1)
          wordcloud(words = Most_Key_LR$Var1, freq = Most_Key_LR$Freq, min.freq = 1,
                    max.words=14, random.order=FALSE, rot.per=0.35, 
                    colors=brewer.pal(8, "Dark2"))

 #Graphics of most frequent group words of Owners 
    #Active Group
          barplot(Most_Key_AO$Freq, las = 2, names.arg = Most_Key_AO$Var1,
                  col ="lightblue", main ="Freq. words of Active Owners",
                  ylab = "Word frequencies")
          set.seed(1)
          wordcloud(words = Most_Key_AO$Var1, freq = Most_Key_AO$Freq, min.freq = 1,
                    max.words=15, random.order=FALSE, rot.per=0.35, 
                    colors=brewer.pal(8, "Dark2"))
          
          #Median Group
          barplot(Most_Key_MO$Freq, las = 2, names.arg = Most_Key_MO$Var1,
                  col ="lightgreen", main ="Freq. words of Median Owners",
                  ylab = "Word frequencies")
          
          set.seed(1)
          wordcloud(words = Most_Key_MO$Var1, freq = Most_Key_MO$Freq, min.freq = 1,
                    max.words=15, random.order=FALSE, rot.per=0.35, 
                    colors=brewer.pal(8, "Dark2"))
          
           #Alien Group
          barplot(Most_Key_LO$Freq, las = 2, names.arg = Most_Key_LO$Var1,
                  col ="deeppink1", main ="Freq. words of Median Owners",
                  ylab = "Word frequencies")
          
          set.seed(1)
          wordcloud(words = Most_Key_LO$Var1, freq = Most_Key_LO$Freq, min.freq = 1,
                    max.words=14, random.order=FALSE, rot.per=0.35, 
                    colors=brewer.pal(8, "Dark2"))




```



