---
title: "Statistical Inference"
author: "Viviane Schneider"
date: "27/08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Statistical Inference Course 

1: Introduction 
2: Probability1 
3: Probability2        
4: ConditionalProbability
5: Expectations
6: Variance  
7: CommonDistros 
8: Asymptotics   
9: T Confidence Intervals
10: Hypothesis Testing  
11: P Values 
12: Power         
13: Multiple Testing  
14: Resampling 

#1: Introduction  
What is?
The process of drawing conclusions "about a population using noisy statistical data where uncertainty must be accounted for". In other words, statistical inference lets scientists formulate conclusions from data and quantify the uncertainty arising from using incomplete data.

Examples:
1: Polling before an election to predict its outcome
2: Constructing a medical image from fMRI data
3: Testing the efficacy of a new drug

So statistical inference involves formulating conclusions using data AND quantifying the uncertainty associated with those conclusions. The uncertainty could arise from incomplete or bad data.

Bad data can be:
1: Selection bias
2: A poorly designed study
3: Small sample size

So with statistical inference we use data to draw general conclusions about a population. 
Which of the following would a scientist using statistical inference techniques consider a problem?

1: Our data sample is representative of the population
2: Our study has no bias and is well-designed

The following is NOT an example of statistical inference in action

1: Testing the effectiveness of a medical treatment
2: Estimating the proportion of people who will vote for a candidate
3: Determining a causative mechanism underlying a disease

Important points:
1: a statistic (singular) is a number computed from a sample of data. We use statistics to infer information about a population.
2: a random variable is an outcome from an experiment. Deterministic processes, such as computing means or variances, applied to random variables, produce additional random variables which have their own distributions. It's important to keep straight which distributions you're talking about.
3: there are two broad flavors of inference. The first is frequency, which uses "long run proportion of times an event occurs in independent, identically distributed repetitions." The second is Bayesian in which the probability estimate for a hypothesis is updated as additional evidence is acquired. Both flavors require an understanding of probability so that's what the next lessons will cover.


#1: Probability1

 In this lesson, we'll review basic ideas of probability, the study of quantifying the likelihood of particular events occurring. Note the similarity between the words probability and probably. Every time you use the latter word you're implying that an event is more likely than not to occur.
 
The first step in understanding probability is to see if you understand what outcomes of an
experiment are possible. For instance, if you were rolling a single, fair die once, how many  outcomes are possible?
6

The probability of a particular outcome of an experiment is the ratio of the number of ways
that outcome can occur to all possible outcomes of the experiment. Since there are 6 possible
outcomes to the experiment of rolling a die, and we assume the die is fair, each outcome is
equally likely. So what is the probability of rolling a 2?
1/6

| What is the probability of rolling an even number?
1/2

Since the probability of a particular outcome or event E is the ratio of ways that E could
occur to the number of all possible outcomes or events, the probability of E, denoted P(E), is
always between 0 and 1. Impossible events have a probability of 0 (since they can't occur) and
events that are certain to occur have a probability of 1.

If you're doing an experiment with n possible outcomes, say e1, e2, ..., en, then the sum of
the probabilities of all the outcomes is 1. If all the outcomes are equally likely, as in the
case of a fair die, then the probability of each is 1/n.

If A and B are two independent events then the probability of them both occurring is the
product of the probabilities. P(A&B) = P(A) * P(B)

Suppose you rolled the fair die twice in succession. What is the probability of rolling two 4's?

The probability of rolling the first 4 is 1/6. The second roll of the dice doesn't depend on
the outcome of the first, so that also has a probability of 1/6. The probability of both events occurring is 1/6 * 1/6. This makes intuitive sense since the probability of 2 such events occurring has to be smaller than the probability of only 1 event.
1/36

Suppose you rolled the fair die twice. What is the probability of rolling the same number two
times in a row?
1/6

Now consider the experiment of rolling 2 dice, one red and one green. Assume the dice are fair and not loaded. How many distinct outcomes are possible?
36

If an event E can occur in more than one way and these ways are disjoint (mutually exclusive) then P(E) is the sum of the probabilities of each of the ways in which it can occur.

Rolling these two dice, what's the probability of rolling a 10?
Since the highest possible dice roll is a '6', the only combinations which give '10' are 4+6
and 5+5. The first occurs in two ways - red dice gets '4' and green gets '6' OR red gets '6'
and green gets '4'.
3/36

What sum is the most likely when rolling these two dice?
The choice of '1' is impossible rolling two dice, and '2' and '12' each occur in only one
possible way (snake-eyes and double 6's, respectively), so '7' and '9' are the only reasonable
choices. To roll '7' you can use any number from '1' to '6', while '9' can only use outcomes of '3' and above.
1: 2
2: 1
3: 12
4: 7
5: 9
7

The probability of at least one of two events, A and B, occurring is the sum of their
individual probabilities minus the probability of their intersection. P(A U B) = P(A) + P(B) - P(A&B).

It's easy to see why this is. Calculating P(A) and P(B) counts outcomes that are in both A and B twice, so they're overcounted. The probability of the intersection of the two events, denoted as A&B, must be subtracted from the sum.

Back to rolling two dice. Which expression represents the probability of rolling an even number or a number greater than 8?
(18+10-4)/36

 It follows that if A and B are disjoint or mutually exclusive, i.e. only one of them can occur, then P(A U B) = P(A)+P(B).
 
 Which of the following expressions represents the probability of rolling a number greater than 10?
 (2+1)/36
 
Use the answer to the previous question and the fact that the sum of all outcomes must sum to 1 to determine the probability of rolling a number less than or equal to 10.
11/12
0.9166667

 A deck of cards is a set of 52 cards, 4 suits of 13 cards each. There are two red suits,
diamonds and hearts, and two black suits, spades and clubs. Each of the 13 cards in a suit has
a value - an ace which is sometimes thought of as 1, a number from 2 to 10, and 3 face cards,
king, queen, and jack. We've created a deck in R for you. Type 'deck' to see it now.

 deck
      spades      hearts      diamonds      clubs     
 [1,] "A:spades"  "A:hearts"  "A:diamonds"  "A:clubs" 
 [2,] "2:spades"  "2:hearts"  "2:diamonds"  "2:clubs" 
 [3,] "3:spades"  "3:hearts"  "3:diamonds"  "3:clubs" 
 [4,] "4:spades"  "4:hearts"  "4:diamonds"  "4:clubs" 
 [5,] "5:spades"  "5:hearts"  "5:diamonds"  "5:clubs" 
 [6,] "6:spades"  "6:hearts"  "6:diamonds"  "6:clubs" 
 [7,] "7:spades"  "7:hearts"  "7:diamonds"  "7:clubs" 
 [8,] "8:spades"  "8:hearts"  "8:diamonds"  "8:clubs" 
 [9,] "9:spades"  "9:hearts"  "9:diamonds"  "9:clubs" 
[10,] "10:spades" "10:hearts" "10:diamonds" "10:clubs"
[11,] "J:spades"  "J:hearts"  "J:diamonds"  "J:clubs" 
[12,] "Q:spades"  "Q:hearts"  "Q:diamonds"  "Q:clubs" 
[13,] "K:spades"  "K:hearts"  "K:diamonds"  "K:clubs" 

When drawing a single card, how many outcomes are possible?
52

What is the probability of drawing a jack?
4/52
0.07692308

If you're dealt a hand of 5 cards, what is the probability of getting all 5 of the same value?
0

What is the probability of drawing a face card?
3/13
0.2307692

Suppose you draw a face card and don't replace it in the deck. What is the probability that when you draw a second card it also will be a face card?
11/51

Suppose you draw a face card and don't replace it in the deck. What is the probability that when you draw a second card it also will be a face card of the same suit?
2/51
0.03921569

  basic probability
|===================================================================================== 
## 12: Power 

In this lesson, as the name suggests, we'll discuss POWER, which is the probability of rejecting the null hypothesis when it is false, which is good and proper.
Power comes into play when you're designing an experiment, and in particular, if you're trying to determine if a null result (failing to reject a null hypothesis) is meaningful. For instance, you might have to determine if your sample size was big enough to yield a meaningful, rather than random, result.

Power gives you the opportunity to detect if your ALTERNATIVE hypothesis is true.

