---
title: "United States communities:"
author: "Viviane Schneider"
date: "28/08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Chalenges - https://towardsdatascience.com/getting-and-cleaning-data-jhu-coursera-course-3-c3635747858b#.y93kqfa0u


## United States communities (USAComu).

Data: https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FPUMSDataDict06.pdf

Code Book:https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FPUMSDataDict06.pdf 

```{r USAComu}

library(readr)
library(dplyr)
library(tidyr)
download.file('https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv'
              , 'ACS.csv'
              , method='curl' )

```



```{r pressure, echo=FALSE}

# Create a logical vector that identifies the households on greater than 10 acres who sold more #than $10,000 worth of agriculture products. Assign that logical vector to the variable #agricultureLogical. Apply the which() function like this to identify the rows of the data #frame where the logical vector is TRUE. which(agricultureLogical)


# Read data into data.frame
#Tests
USAComu <- read.csv('ACS.csv')

View(USAComu)

agricultureLogical <- USAComu$ACR == 3 & USAComu$AGS == 6
head(which(agricultureLogical), 3)

#ST State Code = 48 TEXAS
#TYPE  = 1 HOUSING UNITY
#ACR LOTE SIZE = 1 LESS 1 ACRE 
#BDS BEDROOMS >= 2
#RNTP RENT <= 2000
#VACS VACANCY STATUS = 1

houses <- filter(USAComu, ACR == 1, BDS >= 2, RNTP <= 2000, VACS == 1)

```

Using the jpeg package read in the following picture of your instructor into R

https://d396qusza40orc.cloudfront.net/getdata%2Fjeff.jpg

Use the parameter native=TRUE. What are the 30th and 80th quantiles of the resulting data?


```{r}
library(readr)
library(dplyr)
library(tidyr)
library(jpeg)

# Download the file
download.file('https://d396qusza40orc.cloudfront.net/getdata%2Fjeff.jpg'
              , 'jeff.jpg'
              , mode='wb' )

# Read the image
picture <- jpeg::readJPEG('jeff.jpg'
                          , native=TRUE)

# Get Sample Quantiles corressponding to given prob
quantile(picture, probs = c(0.3, 0.8) )

  
```


